name = "findora_api"
main = "src/api/index.ts"
compatibility_date = "2024-12-05"

routes = [
  { pattern = "findora.turingcorp.net", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "findora_db"
database_id = "67e67029-725a-499f-b4d6-f2969a3f8073"
migrations_dir = "migrations"

[assets]
directory = "src/pages"

[vars]
AI_PROVIDER = "openai"

[triggers]
crons = ["0 9 * * 4"]
