name = "tank-worker"
main = "src/index.js"
compatibility_date = "2024-07-01"

routes = [
  "zhanglingxiao.com/games/tank*",
  "www.zhanglingxiao.com/games/tank*"
]

[assets]
directory = "./public"
binding = "ASSETS"
